repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.9.3
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 21.11b1
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-added-large-files
            args: ["--maxkb=128"]
          - id: check-ast
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: pretty-format-json
            args: ["--autofix", "--no-sort-keys", "--indent=4"]
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.4.1
      hooks:
          - id: prettier
            files: .*[.](md|yml|yaml|js)
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            args: [--config=python/setup.cfg]
            additional_dependencies:
                - flake8-assertive
                - flake8-builtins
                - flake8-comprehensions
                - flake8-logging-format
                - flake8-eradicate
                - flake8-bugbear
    - repo: https://github.com/gruntwork-io/pre-commit
      rev: v0.1.17
      hooks:
          - id: shellcheck
