repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.16
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 19.3b0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
          - id: check-byte-order-marker
          - id: flake8
          - id: check-json
          - id: check-yaml
          - id: detect-private-key
          - id: pretty-format-json
            args: ["--autofix", "--no-sort-keys", "--indent=4"]
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: trailing-whitespace
    - repo: https://github.com/prettier/prettier
      rev: 1.16.2
      hooks:
          - id: prettier
            files: .*[.](md|yml|yaml|js)
