repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
            args: ["--maxkb=128"]
          - id: check-ast
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: pretty-format-json
            args: ["--autofix", "--no-sort-keys", "--indent=4"]
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0
      hooks:
          - id: prettier
            files: .*[.](md|yml|yaml|js)
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            args: [--config=python/setup.cfg]
            additional_dependencies:
                - flake8-assertive
                - flake8-builtins
                - flake8-comprehensions
                - flake8-logging-format
                - flake8-eradicate
                - flake8-bugbear
    - repo: https://github.com/gruntwork-io/pre-commit
      rev: v0.1.22
      hooks:
          - id: shellcheck
